package edu.xww.db.mapper;

import edu.xww.db.model.ContentArticle;
import edu.xww.db.model.ContentArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentArticleMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    long countByExample(ContentArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int deleteByExample(ContentArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int insert(ContentArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int insertSelective(ContentArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    List<ContentArticle> selectByExampleWithBLOBs(ContentArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    List<ContentArticle> selectByExample(ContentArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    ContentArticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") ContentArticle record, @Param("example") ContentArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") ContentArticle record, @Param("example") ContentArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByExample(@Param("record") ContentArticle record, @Param("example") ContentArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByPrimaryKeySelective(ContentArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(ContentArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByPrimaryKey(ContentArticle record);
}