package edu.xww.db.mapper;

import edu.xww.db.model.ContentPage;
import edu.xww.db.model.ContentPageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentPageMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    long countByExample(ContentPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int deleteByExample(ContentPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int insert(ContentPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int insertSelective(ContentPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    List<ContentPage> selectByExampleWithBLOBs(ContentPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    List<ContentPage> selectByExample(ContentPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    ContentPage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") ContentPage record, @Param("example") ContentPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") ContentPage record, @Param("example") ContentPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByExample(@Param("record") ContentPage record, @Param("example") ContentPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByPrimaryKeySelective(ContentPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(ContentPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByPrimaryKey(ContentPage record);
}