package edu.xww.db.mapper;

import edu.xww.db.model.ContentNav;
import edu.xww.db.model.ContentNavExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentNavMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_nav
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    long countByExample(ContentNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_nav
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int deleteByExample(ContentNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_nav
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_nav
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int insert(ContentNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_nav
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int insertSelective(ContentNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_nav
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    List<ContentNav> selectByExample(ContentNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_nav
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    ContentNav selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_nav
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") ContentNav record, @Param("example") ContentNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_nav
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByExample(@Param("record") ContentNav record, @Param("example") ContentNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_nav
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByPrimaryKeySelective(ContentNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_nav
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByPrimaryKey(ContentNav record);
}