package edu.xww.db.mapper;

import edu.xww.db.model.ContentBanner;
import edu.xww.db.model.ContentBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentBannerMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_banner
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    long countByExample(ContentBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_banner
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int deleteByExample(ContentBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_banner
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_banner
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int insert(ContentBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_banner
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int insertSelective(ContentBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_banner
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    List<ContentBanner> selectByExample(ContentBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_banner
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    ContentBanner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_banner
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") ContentBanner record, @Param("example") ContentBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_banner
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByExample(@Param("record") ContentBanner record, @Param("example") ContentBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_banner
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByPrimaryKeySelective(ContentBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_banner
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByPrimaryKey(ContentBanner record);
}