package edu.xww.db.mapper;

import edu.xww.db.model.SystemTemplate;
import edu.xww.db.model.SystemTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemTemplateMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    long countByExample(SystemTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int deleteByExample(SystemTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int insert(SystemTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int insertSelective(SystemTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    List<SystemTemplate> selectByExampleWithBLOBs(SystemTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    List<SystemTemplate> selectByExample(SystemTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    SystemTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") SystemTemplate record, @Param("example") SystemTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") SystemTemplate record, @Param("example") SystemTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByExample(@Param("record") SystemTemplate record, @Param("example") SystemTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByPrimaryKeySelective(SystemTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(SystemTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    int updateByPrimaryKey(SystemTemplate record);
}