package edu.xww.db.model;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString(callSuper=true)
public class ContentNav extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_nav.pid
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_nav.level
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_nav.nav_name
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String navName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_nav.nav_url
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String navUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_nav.nav_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String navType;
}