package edu.xww.db.model;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString(callSuper=true)
public class ContentType extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.pid
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.level
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.type_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private Integer typeTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.content_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private Integer contentTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.type_folder
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String typeFolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.type_name
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.type_sort
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private Integer typeSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.type_click
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private Integer typeClick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.type_title
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String typeTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.type_keywords
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String typeKeywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.type_description
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String typeDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_type.type_content
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String typeContent;
}