package edu.xww.db.model;

import java.util.Date;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString(callSuper=true)
public class ContentPage extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_page.content_template
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private Integer contentTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_page.page_name
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String pageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_page.page_thumb
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String pageThumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_page.page_author
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String pageAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_page.page_time
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private Date pageTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_page.page_click
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private Integer pageClick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_page.page_title
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String pageTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_page.page_keywords
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String pageKeywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_page.page_description
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String pageDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_page.page_flag
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String pageFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_page.page_content
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String pageContent;
}