package edu.xww.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContentTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public ContentTypeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("type.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("type.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("type.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("type.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("type.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("type.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("type.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("type.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("type.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("type.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("type.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("type.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("type.pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("type.pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("type.pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("type.pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("type.pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("type.pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("type.pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("type.pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("type.pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("type.pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("type.pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("type.pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("type.level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("type.level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("type.level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("type.level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("type.level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("type.level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("type.level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("type.level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("type.level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("type.level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("type.level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("type.level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andTypeTemplateIsNull() {
            addCriterion("type.type_template is null");
            return (Criteria) this;
        }

        public Criteria andTypeTemplateIsNotNull() {
            addCriterion("type.type_template is not null");
            return (Criteria) this;
        }

        public Criteria andTypeTemplateEqualTo(Integer value) {
            addCriterion("type.type_template =", value, "typeTemplate");
            return (Criteria) this;
        }

        public Criteria andTypeTemplateNotEqualTo(Integer value) {
            addCriterion("type.type_template <>", value, "typeTemplate");
            return (Criteria) this;
        }

        public Criteria andTypeTemplateGreaterThan(Integer value) {
            addCriterion("type.type_template >", value, "typeTemplate");
            return (Criteria) this;
        }

        public Criteria andTypeTemplateGreaterThanOrEqualTo(Integer value) {
            addCriterion("type.type_template >=", value, "typeTemplate");
            return (Criteria) this;
        }

        public Criteria andTypeTemplateLessThan(Integer value) {
            addCriterion("type.type_template <", value, "typeTemplate");
            return (Criteria) this;
        }

        public Criteria andTypeTemplateLessThanOrEqualTo(Integer value) {
            addCriterion("type.type_template <=", value, "typeTemplate");
            return (Criteria) this;
        }

        public Criteria andTypeTemplateIn(List<Integer> values) {
            addCriterion("type.type_template in", values, "typeTemplate");
            return (Criteria) this;
        }

        public Criteria andTypeTemplateNotIn(List<Integer> values) {
            addCriterion("type.type_template not in", values, "typeTemplate");
            return (Criteria) this;
        }

        public Criteria andTypeTemplateBetween(Integer value1, Integer value2) {
            addCriterion("type.type_template between", value1, value2, "typeTemplate");
            return (Criteria) this;
        }

        public Criteria andTypeTemplateNotBetween(Integer value1, Integer value2) {
            addCriterion("type.type_template not between", value1, value2, "typeTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateIsNull() {
            addCriterion("type.content_template is null");
            return (Criteria) this;
        }

        public Criteria andContentTemplateIsNotNull() {
            addCriterion("type.content_template is not null");
            return (Criteria) this;
        }

        public Criteria andContentTemplateEqualTo(Integer value) {
            addCriterion("type.content_template =", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateNotEqualTo(Integer value) {
            addCriterion("type.content_template <>", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateGreaterThan(Integer value) {
            addCriterion("type.content_template >", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateGreaterThanOrEqualTo(Integer value) {
            addCriterion("type.content_template >=", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateLessThan(Integer value) {
            addCriterion("type.content_template <", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateLessThanOrEqualTo(Integer value) {
            addCriterion("type.content_template <=", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateIn(List<Integer> values) {
            addCriterion("type.content_template in", values, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateNotIn(List<Integer> values) {
            addCriterion("type.content_template not in", values, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateBetween(Integer value1, Integer value2) {
            addCriterion("type.content_template between", value1, value2, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateNotBetween(Integer value1, Integer value2) {
            addCriterion("type.content_template not between", value1, value2, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andTypeFolderIsNull() {
            addCriterion("type.type_folder is null");
            return (Criteria) this;
        }

        public Criteria andTypeFolderIsNotNull() {
            addCriterion("type.type_folder is not null");
            return (Criteria) this;
        }

        public Criteria andTypeFolderEqualTo(String value) {
            addCriterion("type.type_folder =", value, "typeFolder");
            return (Criteria) this;
        }

        public Criteria andTypeFolderNotEqualTo(String value) {
            addCriterion("type.type_folder <>", value, "typeFolder");
            return (Criteria) this;
        }

        public Criteria andTypeFolderGreaterThan(String value) {
            addCriterion("type.type_folder >", value, "typeFolder");
            return (Criteria) this;
        }

        public Criteria andTypeFolderGreaterThanOrEqualTo(String value) {
            addCriterion("type.type_folder >=", value, "typeFolder");
            return (Criteria) this;
        }

        public Criteria andTypeFolderLessThan(String value) {
            addCriterion("type.type_folder <", value, "typeFolder");
            return (Criteria) this;
        }

        public Criteria andTypeFolderLessThanOrEqualTo(String value) {
            addCriterion("type.type_folder <=", value, "typeFolder");
            return (Criteria) this;
        }

        public Criteria andTypeFolderLike(String value) {
            addCriterion("type.type_folder like", value, "typeFolder");
            return (Criteria) this;
        }

        public Criteria andTypeFolderNotLike(String value) {
            addCriterion("type.type_folder not like", value, "typeFolder");
            return (Criteria) this;
        }

        public Criteria andTypeFolderIn(List<String> values) {
            addCriterion("type.type_folder in", values, "typeFolder");
            return (Criteria) this;
        }

        public Criteria andTypeFolderNotIn(List<String> values) {
            addCriterion("type.type_folder not in", values, "typeFolder");
            return (Criteria) this;
        }

        public Criteria andTypeFolderBetween(String value1, String value2) {
            addCriterion("type.type_folder between", value1, value2, "typeFolder");
            return (Criteria) this;
        }

        public Criteria andTypeFolderNotBetween(String value1, String value2) {
            addCriterion("type.type_folder not between", value1, value2, "typeFolder");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNull() {
            addCriterion("type.type_name is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNotNull() {
            addCriterion("type.type_name is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEqualTo(String value) {
            addCriterion("type.type_name =", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotEqualTo(String value) {
            addCriterion("type.type_name <>", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThan(String value) {
            addCriterion("type.type_name >", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("type.type_name >=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThan(String value) {
            addCriterion("type.type_name <", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThanOrEqualTo(String value) {
            addCriterion("type.type_name <=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLike(String value) {
            addCriterion("type.type_name like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotLike(String value) {
            addCriterion("type.type_name not like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameIn(List<String> values) {
            addCriterion("type.type_name in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotIn(List<String> values) {
            addCriterion("type.type_name not in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameBetween(String value1, String value2) {
            addCriterion("type.type_name between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotBetween(String value1, String value2) {
            addCriterion("type.type_name not between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeSortIsNull() {
            addCriterion("type.type_sort is null");
            return (Criteria) this;
        }

        public Criteria andTypeSortIsNotNull() {
            addCriterion("type.type_sort is not null");
            return (Criteria) this;
        }

        public Criteria andTypeSortEqualTo(Integer value) {
            addCriterion("type.type_sort =", value, "typeSort");
            return (Criteria) this;
        }

        public Criteria andTypeSortNotEqualTo(Integer value) {
            addCriterion("type.type_sort <>", value, "typeSort");
            return (Criteria) this;
        }

        public Criteria andTypeSortGreaterThan(Integer value) {
            addCriterion("type.type_sort >", value, "typeSort");
            return (Criteria) this;
        }

        public Criteria andTypeSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("type.type_sort >=", value, "typeSort");
            return (Criteria) this;
        }

        public Criteria andTypeSortLessThan(Integer value) {
            addCriterion("type.type_sort <", value, "typeSort");
            return (Criteria) this;
        }

        public Criteria andTypeSortLessThanOrEqualTo(Integer value) {
            addCriterion("type.type_sort <=", value, "typeSort");
            return (Criteria) this;
        }

        public Criteria andTypeSortIn(List<Integer> values) {
            addCriterion("type.type_sort in", values, "typeSort");
            return (Criteria) this;
        }

        public Criteria andTypeSortNotIn(List<Integer> values) {
            addCriterion("type.type_sort not in", values, "typeSort");
            return (Criteria) this;
        }

        public Criteria andTypeSortBetween(Integer value1, Integer value2) {
            addCriterion("type.type_sort between", value1, value2, "typeSort");
            return (Criteria) this;
        }

        public Criteria andTypeSortNotBetween(Integer value1, Integer value2) {
            addCriterion("type.type_sort not between", value1, value2, "typeSort");
            return (Criteria) this;
        }

        public Criteria andTypeClickIsNull() {
            addCriterion("type.type_click is null");
            return (Criteria) this;
        }

        public Criteria andTypeClickIsNotNull() {
            addCriterion("type.type_click is not null");
            return (Criteria) this;
        }

        public Criteria andTypeClickEqualTo(Integer value) {
            addCriterion("type.type_click =", value, "typeClick");
            return (Criteria) this;
        }

        public Criteria andTypeClickNotEqualTo(Integer value) {
            addCriterion("type.type_click <>", value, "typeClick");
            return (Criteria) this;
        }

        public Criteria andTypeClickGreaterThan(Integer value) {
            addCriterion("type.type_click >", value, "typeClick");
            return (Criteria) this;
        }

        public Criteria andTypeClickGreaterThanOrEqualTo(Integer value) {
            addCriterion("type.type_click >=", value, "typeClick");
            return (Criteria) this;
        }

        public Criteria andTypeClickLessThan(Integer value) {
            addCriterion("type.type_click <", value, "typeClick");
            return (Criteria) this;
        }

        public Criteria andTypeClickLessThanOrEqualTo(Integer value) {
            addCriterion("type.type_click <=", value, "typeClick");
            return (Criteria) this;
        }

        public Criteria andTypeClickIn(List<Integer> values) {
            addCriterion("type.type_click in", values, "typeClick");
            return (Criteria) this;
        }

        public Criteria andTypeClickNotIn(List<Integer> values) {
            addCriterion("type.type_click not in", values, "typeClick");
            return (Criteria) this;
        }

        public Criteria andTypeClickBetween(Integer value1, Integer value2) {
            addCriterion("type.type_click between", value1, value2, "typeClick");
            return (Criteria) this;
        }

        public Criteria andTypeClickNotBetween(Integer value1, Integer value2) {
            addCriterion("type.type_click not between", value1, value2, "typeClick");
            return (Criteria) this;
        }

        public Criteria andTypeTitleIsNull() {
            addCriterion("type.type_title is null");
            return (Criteria) this;
        }

        public Criteria andTypeTitleIsNotNull() {
            addCriterion("type.type_title is not null");
            return (Criteria) this;
        }

        public Criteria andTypeTitleEqualTo(String value) {
            addCriterion("type.type_title =", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleNotEqualTo(String value) {
            addCriterion("type.type_title <>", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleGreaterThan(String value) {
            addCriterion("type.type_title >", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleGreaterThanOrEqualTo(String value) {
            addCriterion("type.type_title >=", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleLessThan(String value) {
            addCriterion("type.type_title <", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleLessThanOrEqualTo(String value) {
            addCriterion("type.type_title <=", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleLike(String value) {
            addCriterion("type.type_title like", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleNotLike(String value) {
            addCriterion("type.type_title not like", value, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleIn(List<String> values) {
            addCriterion("type.type_title in", values, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleNotIn(List<String> values) {
            addCriterion("type.type_title not in", values, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleBetween(String value1, String value2) {
            addCriterion("type.type_title between", value1, value2, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeTitleNotBetween(String value1, String value2) {
            addCriterion("type.type_title not between", value1, value2, "typeTitle");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsIsNull() {
            addCriterion("type.type_keywords is null");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsIsNotNull() {
            addCriterion("type.type_keywords is not null");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsEqualTo(String value) {
            addCriterion("type.type_keywords =", value, "typeKeywords");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsNotEqualTo(String value) {
            addCriterion("type.type_keywords <>", value, "typeKeywords");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsGreaterThan(String value) {
            addCriterion("type.type_keywords >", value, "typeKeywords");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("type.type_keywords >=", value, "typeKeywords");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsLessThan(String value) {
            addCriterion("type.type_keywords <", value, "typeKeywords");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsLessThanOrEqualTo(String value) {
            addCriterion("type.type_keywords <=", value, "typeKeywords");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsLike(String value) {
            addCriterion("type.type_keywords like", value, "typeKeywords");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsNotLike(String value) {
            addCriterion("type.type_keywords not like", value, "typeKeywords");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsIn(List<String> values) {
            addCriterion("type.type_keywords in", values, "typeKeywords");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsNotIn(List<String> values) {
            addCriterion("type.type_keywords not in", values, "typeKeywords");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsBetween(String value1, String value2) {
            addCriterion("type.type_keywords between", value1, value2, "typeKeywords");
            return (Criteria) this;
        }

        public Criteria andTypeKeywordsNotBetween(String value1, String value2) {
            addCriterion("type.type_keywords not between", value1, value2, "typeKeywords");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionIsNull() {
            addCriterion("type.type_description is null");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionIsNotNull() {
            addCriterion("type.type_description is not null");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionEqualTo(String value) {
            addCriterion("type.type_description =", value, "typeDescription");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionNotEqualTo(String value) {
            addCriterion("type.type_description <>", value, "typeDescription");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionGreaterThan(String value) {
            addCriterion("type.type_description >", value, "typeDescription");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("type.type_description >=", value, "typeDescription");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionLessThan(String value) {
            addCriterion("type.type_description <", value, "typeDescription");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionLessThanOrEqualTo(String value) {
            addCriterion("type.type_description <=", value, "typeDescription");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionLike(String value) {
            addCriterion("type.type_description like", value, "typeDescription");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionNotLike(String value) {
            addCriterion("type.type_description not like", value, "typeDescription");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionIn(List<String> values) {
            addCriterion("type.type_description in", values, "typeDescription");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionNotIn(List<String> values) {
            addCriterion("type.type_description not in", values, "typeDescription");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionBetween(String value1, String value2) {
            addCriterion("type.type_description between", value1, value2, "typeDescription");
            return (Criteria) this;
        }

        public Criteria andTypeDescriptionNotBetween(String value1, String value2) {
            addCriterion("type.type_description not between", value1, value2, "typeDescription");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("type.add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("type.add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("type.add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("type.add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("type.add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("type.add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("type.add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("type.add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("type.add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("type.add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("type.add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("type.add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("type.update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("type.update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("type.update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("type.update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("type.update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("type.update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("type.update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("type.update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("type.update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("type.update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("type.update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("type.update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeIsNull() {
            addCriterion("type.del_time is null");
            return (Criteria) this;
        }

        public Criteria andDelTimeIsNotNull() {
            addCriterion("type.del_time is not null");
            return (Criteria) this;
        }

        public Criteria andDelTimeEqualTo(Integer value) {
            addCriterion("type.del_time =", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotEqualTo(Integer value) {
            addCriterion("type.del_time <>", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeGreaterThan(Integer value) {
            addCriterion("type.del_time >", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type.del_time >=", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeLessThan(Integer value) {
            addCriterion("type.del_time <", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeLessThanOrEqualTo(Integer value) {
            addCriterion("type.del_time <=", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeIn(List<Integer> values) {
            addCriterion("type.del_time in", values, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotIn(List<Integer> values) {
            addCriterion("type.del_time not in", values, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeBetween(Integer value1, Integer value2) {
            addCriterion("type.del_time between", value1, value2, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("type.del_time not between", value1, value2, "delTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content_type
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 04 10:36:30 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}