package edu.xww.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContentPageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public ContentPageExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("page.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("page.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("page.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("page.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("page.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("page.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("page.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("page.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("page.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("page.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("page.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("page.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andContentTemplateIsNull() {
            addCriterion("page.content_template is null");
            return (Criteria) this;
        }

        public Criteria andContentTemplateIsNotNull() {
            addCriterion("page.content_template is not null");
            return (Criteria) this;
        }

        public Criteria andContentTemplateEqualTo(Integer value) {
            addCriterion("page.content_template =", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateNotEqualTo(Integer value) {
            addCriterion("page.content_template <>", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateGreaterThan(Integer value) {
            addCriterion("page.content_template >", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateGreaterThanOrEqualTo(Integer value) {
            addCriterion("page.content_template >=", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateLessThan(Integer value) {
            addCriterion("page.content_template <", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateLessThanOrEqualTo(Integer value) {
            addCriterion("page.content_template <=", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateIn(List<Integer> values) {
            addCriterion("page.content_template in", values, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateNotIn(List<Integer> values) {
            addCriterion("page.content_template not in", values, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateBetween(Integer value1, Integer value2) {
            addCriterion("page.content_template between", value1, value2, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateNotBetween(Integer value1, Integer value2) {
            addCriterion("page.content_template not between", value1, value2, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andPageNameIsNull() {
            addCriterion("page.page_name is null");
            return (Criteria) this;
        }

        public Criteria andPageNameIsNotNull() {
            addCriterion("page.page_name is not null");
            return (Criteria) this;
        }

        public Criteria andPageNameEqualTo(String value) {
            addCriterion("page.page_name =", value, "pageName");
            return (Criteria) this;
        }

        public Criteria andPageNameNotEqualTo(String value) {
            addCriterion("page.page_name <>", value, "pageName");
            return (Criteria) this;
        }

        public Criteria andPageNameGreaterThan(String value) {
            addCriterion("page.page_name >", value, "pageName");
            return (Criteria) this;
        }

        public Criteria andPageNameGreaterThanOrEqualTo(String value) {
            addCriterion("page.page_name >=", value, "pageName");
            return (Criteria) this;
        }

        public Criteria andPageNameLessThan(String value) {
            addCriterion("page.page_name <", value, "pageName");
            return (Criteria) this;
        }

        public Criteria andPageNameLessThanOrEqualTo(String value) {
            addCriterion("page.page_name <=", value, "pageName");
            return (Criteria) this;
        }

        public Criteria andPageNameLike(String value) {
            addCriterion("page.page_name like", value, "pageName");
            return (Criteria) this;
        }

        public Criteria andPageNameNotLike(String value) {
            addCriterion("page.page_name not like", value, "pageName");
            return (Criteria) this;
        }

        public Criteria andPageNameIn(List<String> values) {
            addCriterion("page.page_name in", values, "pageName");
            return (Criteria) this;
        }

        public Criteria andPageNameNotIn(List<String> values) {
            addCriterion("page.page_name not in", values, "pageName");
            return (Criteria) this;
        }

        public Criteria andPageNameBetween(String value1, String value2) {
            addCriterion("page.page_name between", value1, value2, "pageName");
            return (Criteria) this;
        }

        public Criteria andPageNameNotBetween(String value1, String value2) {
            addCriterion("page.page_name not between", value1, value2, "pageName");
            return (Criteria) this;
        }

        public Criteria andPageThumbIsNull() {
            addCriterion("page.page_thumb is null");
            return (Criteria) this;
        }

        public Criteria andPageThumbIsNotNull() {
            addCriterion("page.page_thumb is not null");
            return (Criteria) this;
        }

        public Criteria andPageThumbEqualTo(String value) {
            addCriterion("page.page_thumb =", value, "pageThumb");
            return (Criteria) this;
        }

        public Criteria andPageThumbNotEqualTo(String value) {
            addCriterion("page.page_thumb <>", value, "pageThumb");
            return (Criteria) this;
        }

        public Criteria andPageThumbGreaterThan(String value) {
            addCriterion("page.page_thumb >", value, "pageThumb");
            return (Criteria) this;
        }

        public Criteria andPageThumbGreaterThanOrEqualTo(String value) {
            addCriterion("page.page_thumb >=", value, "pageThumb");
            return (Criteria) this;
        }

        public Criteria andPageThumbLessThan(String value) {
            addCriterion("page.page_thumb <", value, "pageThumb");
            return (Criteria) this;
        }

        public Criteria andPageThumbLessThanOrEqualTo(String value) {
            addCriterion("page.page_thumb <=", value, "pageThumb");
            return (Criteria) this;
        }

        public Criteria andPageThumbLike(String value) {
            addCriterion("page.page_thumb like", value, "pageThumb");
            return (Criteria) this;
        }

        public Criteria andPageThumbNotLike(String value) {
            addCriterion("page.page_thumb not like", value, "pageThumb");
            return (Criteria) this;
        }

        public Criteria andPageThumbIn(List<String> values) {
            addCriterion("page.page_thumb in", values, "pageThumb");
            return (Criteria) this;
        }

        public Criteria andPageThumbNotIn(List<String> values) {
            addCriterion("page.page_thumb not in", values, "pageThumb");
            return (Criteria) this;
        }

        public Criteria andPageThumbBetween(String value1, String value2) {
            addCriterion("page.page_thumb between", value1, value2, "pageThumb");
            return (Criteria) this;
        }

        public Criteria andPageThumbNotBetween(String value1, String value2) {
            addCriterion("page.page_thumb not between", value1, value2, "pageThumb");
            return (Criteria) this;
        }

        public Criteria andPageAuthorIsNull() {
            addCriterion("page.page_author is null");
            return (Criteria) this;
        }

        public Criteria andPageAuthorIsNotNull() {
            addCriterion("page.page_author is not null");
            return (Criteria) this;
        }

        public Criteria andPageAuthorEqualTo(String value) {
            addCriterion("page.page_author =", value, "pageAuthor");
            return (Criteria) this;
        }

        public Criteria andPageAuthorNotEqualTo(String value) {
            addCriterion("page.page_author <>", value, "pageAuthor");
            return (Criteria) this;
        }

        public Criteria andPageAuthorGreaterThan(String value) {
            addCriterion("page.page_author >", value, "pageAuthor");
            return (Criteria) this;
        }

        public Criteria andPageAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("page.page_author >=", value, "pageAuthor");
            return (Criteria) this;
        }

        public Criteria andPageAuthorLessThan(String value) {
            addCriterion("page.page_author <", value, "pageAuthor");
            return (Criteria) this;
        }

        public Criteria andPageAuthorLessThanOrEqualTo(String value) {
            addCriterion("page.page_author <=", value, "pageAuthor");
            return (Criteria) this;
        }

        public Criteria andPageAuthorLike(String value) {
            addCriterion("page.page_author like", value, "pageAuthor");
            return (Criteria) this;
        }

        public Criteria andPageAuthorNotLike(String value) {
            addCriterion("page.page_author not like", value, "pageAuthor");
            return (Criteria) this;
        }

        public Criteria andPageAuthorIn(List<String> values) {
            addCriterion("page.page_author in", values, "pageAuthor");
            return (Criteria) this;
        }

        public Criteria andPageAuthorNotIn(List<String> values) {
            addCriterion("page.page_author not in", values, "pageAuthor");
            return (Criteria) this;
        }

        public Criteria andPageAuthorBetween(String value1, String value2) {
            addCriterion("page.page_author between", value1, value2, "pageAuthor");
            return (Criteria) this;
        }

        public Criteria andPageAuthorNotBetween(String value1, String value2) {
            addCriterion("page.page_author not between", value1, value2, "pageAuthor");
            return (Criteria) this;
        }

        public Criteria andPageTimeIsNull() {
            addCriterion("page.page_time is null");
            return (Criteria) this;
        }

        public Criteria andPageTimeIsNotNull() {
            addCriterion("page.page_time is not null");
            return (Criteria) this;
        }

        public Criteria andPageTimeEqualTo(Date value) {
            addCriterion("page.page_time =", value, "pageTime");
            return (Criteria) this;
        }

        public Criteria andPageTimeNotEqualTo(Date value) {
            addCriterion("page.page_time <>", value, "pageTime");
            return (Criteria) this;
        }

        public Criteria andPageTimeGreaterThan(Date value) {
            addCriterion("page.page_time >", value, "pageTime");
            return (Criteria) this;
        }

        public Criteria andPageTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("page.page_time >=", value, "pageTime");
            return (Criteria) this;
        }

        public Criteria andPageTimeLessThan(Date value) {
            addCriterion("page.page_time <", value, "pageTime");
            return (Criteria) this;
        }

        public Criteria andPageTimeLessThanOrEqualTo(Date value) {
            addCriterion("page.page_time <=", value, "pageTime");
            return (Criteria) this;
        }

        public Criteria andPageTimeIn(List<Date> values) {
            addCriterion("page.page_time in", values, "pageTime");
            return (Criteria) this;
        }

        public Criteria andPageTimeNotIn(List<Date> values) {
            addCriterion("page.page_time not in", values, "pageTime");
            return (Criteria) this;
        }

        public Criteria andPageTimeBetween(Date value1, Date value2) {
            addCriterion("page.page_time between", value1, value2, "pageTime");
            return (Criteria) this;
        }

        public Criteria andPageTimeNotBetween(Date value1, Date value2) {
            addCriterion("page.page_time not between", value1, value2, "pageTime");
            return (Criteria) this;
        }

        public Criteria andPageClickIsNull() {
            addCriterion("page.page_click is null");
            return (Criteria) this;
        }

        public Criteria andPageClickIsNotNull() {
            addCriterion("page.page_click is not null");
            return (Criteria) this;
        }

        public Criteria andPageClickEqualTo(Integer value) {
            addCriterion("page.page_click =", value, "pageClick");
            return (Criteria) this;
        }

        public Criteria andPageClickNotEqualTo(Integer value) {
            addCriterion("page.page_click <>", value, "pageClick");
            return (Criteria) this;
        }

        public Criteria andPageClickGreaterThan(Integer value) {
            addCriterion("page.page_click >", value, "pageClick");
            return (Criteria) this;
        }

        public Criteria andPageClickGreaterThanOrEqualTo(Integer value) {
            addCriterion("page.page_click >=", value, "pageClick");
            return (Criteria) this;
        }

        public Criteria andPageClickLessThan(Integer value) {
            addCriterion("page.page_click <", value, "pageClick");
            return (Criteria) this;
        }

        public Criteria andPageClickLessThanOrEqualTo(Integer value) {
            addCriterion("page.page_click <=", value, "pageClick");
            return (Criteria) this;
        }

        public Criteria andPageClickIn(List<Integer> values) {
            addCriterion("page.page_click in", values, "pageClick");
            return (Criteria) this;
        }

        public Criteria andPageClickNotIn(List<Integer> values) {
            addCriterion("page.page_click not in", values, "pageClick");
            return (Criteria) this;
        }

        public Criteria andPageClickBetween(Integer value1, Integer value2) {
            addCriterion("page.page_click between", value1, value2, "pageClick");
            return (Criteria) this;
        }

        public Criteria andPageClickNotBetween(Integer value1, Integer value2) {
            addCriterion("page.page_click not between", value1, value2, "pageClick");
            return (Criteria) this;
        }

        public Criteria andPageTitleIsNull() {
            addCriterion("page.page_title is null");
            return (Criteria) this;
        }

        public Criteria andPageTitleIsNotNull() {
            addCriterion("page.page_title is not null");
            return (Criteria) this;
        }

        public Criteria andPageTitleEqualTo(String value) {
            addCriterion("page.page_title =", value, "pageTitle");
            return (Criteria) this;
        }

        public Criteria andPageTitleNotEqualTo(String value) {
            addCriterion("page.page_title <>", value, "pageTitle");
            return (Criteria) this;
        }

        public Criteria andPageTitleGreaterThan(String value) {
            addCriterion("page.page_title >", value, "pageTitle");
            return (Criteria) this;
        }

        public Criteria andPageTitleGreaterThanOrEqualTo(String value) {
            addCriterion("page.page_title >=", value, "pageTitle");
            return (Criteria) this;
        }

        public Criteria andPageTitleLessThan(String value) {
            addCriterion("page.page_title <", value, "pageTitle");
            return (Criteria) this;
        }

        public Criteria andPageTitleLessThanOrEqualTo(String value) {
            addCriterion("page.page_title <=", value, "pageTitle");
            return (Criteria) this;
        }

        public Criteria andPageTitleLike(String value) {
            addCriterion("page.page_title like", value, "pageTitle");
            return (Criteria) this;
        }

        public Criteria andPageTitleNotLike(String value) {
            addCriterion("page.page_title not like", value, "pageTitle");
            return (Criteria) this;
        }

        public Criteria andPageTitleIn(List<String> values) {
            addCriterion("page.page_title in", values, "pageTitle");
            return (Criteria) this;
        }

        public Criteria andPageTitleNotIn(List<String> values) {
            addCriterion("page.page_title not in", values, "pageTitle");
            return (Criteria) this;
        }

        public Criteria andPageTitleBetween(String value1, String value2) {
            addCriterion("page.page_title between", value1, value2, "pageTitle");
            return (Criteria) this;
        }

        public Criteria andPageTitleNotBetween(String value1, String value2) {
            addCriterion("page.page_title not between", value1, value2, "pageTitle");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsIsNull() {
            addCriterion("page.page_keywords is null");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsIsNotNull() {
            addCriterion("page.page_keywords is not null");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsEqualTo(String value) {
            addCriterion("page.page_keywords =", value, "pageKeywords");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsNotEqualTo(String value) {
            addCriterion("page.page_keywords <>", value, "pageKeywords");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsGreaterThan(String value) {
            addCriterion("page.page_keywords >", value, "pageKeywords");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("page.page_keywords >=", value, "pageKeywords");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsLessThan(String value) {
            addCriterion("page.page_keywords <", value, "pageKeywords");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsLessThanOrEqualTo(String value) {
            addCriterion("page.page_keywords <=", value, "pageKeywords");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsLike(String value) {
            addCriterion("page.page_keywords like", value, "pageKeywords");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsNotLike(String value) {
            addCriterion("page.page_keywords not like", value, "pageKeywords");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsIn(List<String> values) {
            addCriterion("page.page_keywords in", values, "pageKeywords");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsNotIn(List<String> values) {
            addCriterion("page.page_keywords not in", values, "pageKeywords");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsBetween(String value1, String value2) {
            addCriterion("page.page_keywords between", value1, value2, "pageKeywords");
            return (Criteria) this;
        }

        public Criteria andPageKeywordsNotBetween(String value1, String value2) {
            addCriterion("page.page_keywords not between", value1, value2, "pageKeywords");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionIsNull() {
            addCriterion("page.page_description is null");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionIsNotNull() {
            addCriterion("page.page_description is not null");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionEqualTo(String value) {
            addCriterion("page.page_description =", value, "pageDescription");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionNotEqualTo(String value) {
            addCriterion("page.page_description <>", value, "pageDescription");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionGreaterThan(String value) {
            addCriterion("page.page_description >", value, "pageDescription");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("page.page_description >=", value, "pageDescription");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionLessThan(String value) {
            addCriterion("page.page_description <", value, "pageDescription");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionLessThanOrEqualTo(String value) {
            addCriterion("page.page_description <=", value, "pageDescription");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionLike(String value) {
            addCriterion("page.page_description like", value, "pageDescription");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionNotLike(String value) {
            addCriterion("page.page_description not like", value, "pageDescription");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionIn(List<String> values) {
            addCriterion("page.page_description in", values, "pageDescription");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionNotIn(List<String> values) {
            addCriterion("page.page_description not in", values, "pageDescription");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionBetween(String value1, String value2) {
            addCriterion("page.page_description between", value1, value2, "pageDescription");
            return (Criteria) this;
        }

        public Criteria andPageDescriptionNotBetween(String value1, String value2) {
            addCriterion("page.page_description not between", value1, value2, "pageDescription");
            return (Criteria) this;
        }

        public Criteria andPageFlagIsNull() {
            addCriterion("page.page_flag is null");
            return (Criteria) this;
        }

        public Criteria andPageFlagIsNotNull() {
            addCriterion("page.page_flag is not null");
            return (Criteria) this;
        }

        public Criteria andPageFlagEqualTo(String value) {
            addCriterion("page.page_flag =", value, "pageFlag");
            return (Criteria) this;
        }

        public Criteria andPageFlagNotEqualTo(String value) {
            addCriterion("page.page_flag <>", value, "pageFlag");
            return (Criteria) this;
        }

        public Criteria andPageFlagGreaterThan(String value) {
            addCriterion("page.page_flag >", value, "pageFlag");
            return (Criteria) this;
        }

        public Criteria andPageFlagGreaterThanOrEqualTo(String value) {
            addCriterion("page.page_flag >=", value, "pageFlag");
            return (Criteria) this;
        }

        public Criteria andPageFlagLessThan(String value) {
            addCriterion("page.page_flag <", value, "pageFlag");
            return (Criteria) this;
        }

        public Criteria andPageFlagLessThanOrEqualTo(String value) {
            addCriterion("page.page_flag <=", value, "pageFlag");
            return (Criteria) this;
        }

        public Criteria andPageFlagLike(String value) {
            addCriterion("page.page_flag like", value, "pageFlag");
            return (Criteria) this;
        }

        public Criteria andPageFlagNotLike(String value) {
            addCriterion("page.page_flag not like", value, "pageFlag");
            return (Criteria) this;
        }

        public Criteria andPageFlagIn(List<String> values) {
            addCriterion("page.page_flag in", values, "pageFlag");
            return (Criteria) this;
        }

        public Criteria andPageFlagNotIn(List<String> values) {
            addCriterion("page.page_flag not in", values, "pageFlag");
            return (Criteria) this;
        }

        public Criteria andPageFlagBetween(String value1, String value2) {
            addCriterion("page.page_flag between", value1, value2, "pageFlag");
            return (Criteria) this;
        }

        public Criteria andPageFlagNotBetween(String value1, String value2) {
            addCriterion("page.page_flag not between", value1, value2, "pageFlag");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("page.add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("page.add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("page.add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("page.add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("page.add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("page.add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("page.add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("page.add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("page.add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("page.add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("page.add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("page.add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("page.update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("page.update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("page.update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("page.update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("page.update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("page.update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("page.update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("page.update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("page.update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("page.update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("page.update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("page.update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeIsNull() {
            addCriterion("page.del_time is null");
            return (Criteria) this;
        }

        public Criteria andDelTimeIsNotNull() {
            addCriterion("page.del_time is not null");
            return (Criteria) this;
        }

        public Criteria andDelTimeEqualTo(Integer value) {
            addCriterion("page.del_time =", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotEqualTo(Integer value) {
            addCriterion("page.del_time <>", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeGreaterThan(Integer value) {
            addCriterion("page.del_time >", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("page.del_time >=", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeLessThan(Integer value) {
            addCriterion("page.del_time <", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeLessThanOrEqualTo(Integer value) {
            addCriterion("page.del_time <=", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeIn(List<Integer> values) {
            addCriterion("page.del_time in", values, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotIn(List<Integer> values) {
            addCriterion("page.del_time not in", values, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeBetween(Integer value1, Integer value2) {
            addCriterion("page.del_time between", value1, value2, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("page.del_time not between", value1, value2, "delTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content_page
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 04 10:36:30 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content_page
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}