package edu.xww.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContentArticleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public ContentArticleExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("article.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("article.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("article.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("article.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("article.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("article.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("article.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("article.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("article.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("article.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("article.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("article.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNull() {
            addCriterion("article.type_id is null");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNotNull() {
            addCriterion("article.type_id is not null");
            return (Criteria) this;
        }

        public Criteria andTypeIdEqualTo(Integer value) {
            addCriterion("article.type_id =", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotEqualTo(Integer value) {
            addCriterion("article.type_id <>", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThan(Integer value) {
            addCriterion("article.type_id >", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("article.type_id >=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThan(Integer value) {
            addCriterion("article.type_id <", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("article.type_id <=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIn(List<Integer> values) {
            addCriterion("article.type_id in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotIn(List<Integer> values) {
            addCriterion("article.type_id not in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("article.type_id between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("article.type_id not between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andContentTemplateIsNull() {
            addCriterion("article.content_template is null");
            return (Criteria) this;
        }

        public Criteria andContentTemplateIsNotNull() {
            addCriterion("article.content_template is not null");
            return (Criteria) this;
        }

        public Criteria andContentTemplateEqualTo(Integer value) {
            addCriterion("article.content_template =", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateNotEqualTo(Integer value) {
            addCriterion("article.content_template <>", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateGreaterThan(Integer value) {
            addCriterion("article.content_template >", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateGreaterThanOrEqualTo(Integer value) {
            addCriterion("article.content_template >=", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateLessThan(Integer value) {
            addCriterion("article.content_template <", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateLessThanOrEqualTo(Integer value) {
            addCriterion("article.content_template <=", value, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateIn(List<Integer> values) {
            addCriterion("article.content_template in", values, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateNotIn(List<Integer> values) {
            addCriterion("article.content_template not in", values, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateBetween(Integer value1, Integer value2) {
            addCriterion("article.content_template between", value1, value2, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andContentTemplateNotBetween(Integer value1, Integer value2) {
            addCriterion("article.content_template not between", value1, value2, "contentTemplate");
            return (Criteria) this;
        }

        public Criteria andArticleNameIsNull() {
            addCriterion("article.article_name is null");
            return (Criteria) this;
        }

        public Criteria andArticleNameIsNotNull() {
            addCriterion("article.article_name is not null");
            return (Criteria) this;
        }

        public Criteria andArticleNameEqualTo(String value) {
            addCriterion("article.article_name =", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameNotEqualTo(String value) {
            addCriterion("article.article_name <>", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameGreaterThan(String value) {
            addCriterion("article.article_name >", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameGreaterThanOrEqualTo(String value) {
            addCriterion("article.article_name >=", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameLessThan(String value) {
            addCriterion("article.article_name <", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameLessThanOrEqualTo(String value) {
            addCriterion("article.article_name <=", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameLike(String value) {
            addCriterion("article.article_name like", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameNotLike(String value) {
            addCriterion("article.article_name not like", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameIn(List<String> values) {
            addCriterion("article.article_name in", values, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameNotIn(List<String> values) {
            addCriterion("article.article_name not in", values, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameBetween(String value1, String value2) {
            addCriterion("article.article_name between", value1, value2, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameNotBetween(String value1, String value2) {
            addCriterion("article.article_name not between", value1, value2, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleThumbIsNull() {
            addCriterion("article.article_thumb is null");
            return (Criteria) this;
        }

        public Criteria andArticleThumbIsNotNull() {
            addCriterion("article.article_thumb is not null");
            return (Criteria) this;
        }

        public Criteria andArticleThumbEqualTo(String value) {
            addCriterion("article.article_thumb =", value, "articleThumb");
            return (Criteria) this;
        }

        public Criteria andArticleThumbNotEqualTo(String value) {
            addCriterion("article.article_thumb <>", value, "articleThumb");
            return (Criteria) this;
        }

        public Criteria andArticleThumbGreaterThan(String value) {
            addCriterion("article.article_thumb >", value, "articleThumb");
            return (Criteria) this;
        }

        public Criteria andArticleThumbGreaterThanOrEqualTo(String value) {
            addCriterion("article.article_thumb >=", value, "articleThumb");
            return (Criteria) this;
        }

        public Criteria andArticleThumbLessThan(String value) {
            addCriterion("article.article_thumb <", value, "articleThumb");
            return (Criteria) this;
        }

        public Criteria andArticleThumbLessThanOrEqualTo(String value) {
            addCriterion("article.article_thumb <=", value, "articleThumb");
            return (Criteria) this;
        }

        public Criteria andArticleThumbLike(String value) {
            addCriterion("article.article_thumb like", value, "articleThumb");
            return (Criteria) this;
        }

        public Criteria andArticleThumbNotLike(String value) {
            addCriterion("article.article_thumb not like", value, "articleThumb");
            return (Criteria) this;
        }

        public Criteria andArticleThumbIn(List<String> values) {
            addCriterion("article.article_thumb in", values, "articleThumb");
            return (Criteria) this;
        }

        public Criteria andArticleThumbNotIn(List<String> values) {
            addCriterion("article.article_thumb not in", values, "articleThumb");
            return (Criteria) this;
        }

        public Criteria andArticleThumbBetween(String value1, String value2) {
            addCriterion("article.article_thumb between", value1, value2, "articleThumb");
            return (Criteria) this;
        }

        public Criteria andArticleThumbNotBetween(String value1, String value2) {
            addCriterion("article.article_thumb not between", value1, value2, "articleThumb");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIsNull() {
            addCriterion("article.article_author is null");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIsNotNull() {
            addCriterion("article.article_author is not null");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorEqualTo(String value) {
            addCriterion("article.article_author =", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNotEqualTo(String value) {
            addCriterion("article.article_author <>", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorGreaterThan(String value) {
            addCriterion("article.article_author >", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("article.article_author >=", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorLessThan(String value) {
            addCriterion("article.article_author <", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorLessThanOrEqualTo(String value) {
            addCriterion("article.article_author <=", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorLike(String value) {
            addCriterion("article.article_author like", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNotLike(String value) {
            addCriterion("article.article_author not like", value, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIn(List<String> values) {
            addCriterion("article.article_author in", values, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNotIn(List<String> values) {
            addCriterion("article.article_author not in", values, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorBetween(String value1, String value2) {
            addCriterion("article.article_author between", value1, value2, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNotBetween(String value1, String value2) {
            addCriterion("article.article_author not between", value1, value2, "articleAuthor");
            return (Criteria) this;
        }

        public Criteria andArticleTimeIsNull() {
            addCriterion("article.article_time is null");
            return (Criteria) this;
        }

        public Criteria andArticleTimeIsNotNull() {
            addCriterion("article.article_time is not null");
            return (Criteria) this;
        }

        public Criteria andArticleTimeEqualTo(Date value) {
            addCriterion("article.article_time =", value, "articleTime");
            return (Criteria) this;
        }

        public Criteria andArticleTimeNotEqualTo(Date value) {
            addCriterion("article.article_time <>", value, "articleTime");
            return (Criteria) this;
        }

        public Criteria andArticleTimeGreaterThan(Date value) {
            addCriterion("article.article_time >", value, "articleTime");
            return (Criteria) this;
        }

        public Criteria andArticleTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("article.article_time >=", value, "articleTime");
            return (Criteria) this;
        }

        public Criteria andArticleTimeLessThan(Date value) {
            addCriterion("article.article_time <", value, "articleTime");
            return (Criteria) this;
        }

        public Criteria andArticleTimeLessThanOrEqualTo(Date value) {
            addCriterion("article.article_time <=", value, "articleTime");
            return (Criteria) this;
        }

        public Criteria andArticleTimeIn(List<Date> values) {
            addCriterion("article.article_time in", values, "articleTime");
            return (Criteria) this;
        }

        public Criteria andArticleTimeNotIn(List<Date> values) {
            addCriterion("article.article_time not in", values, "articleTime");
            return (Criteria) this;
        }

        public Criteria andArticleTimeBetween(Date value1, Date value2) {
            addCriterion("article.article_time between", value1, value2, "articleTime");
            return (Criteria) this;
        }

        public Criteria andArticleTimeNotBetween(Date value1, Date value2) {
            addCriterion("article.article_time not between", value1, value2, "articleTime");
            return (Criteria) this;
        }

        public Criteria andArticleClickIsNull() {
            addCriterion("article.article_click is null");
            return (Criteria) this;
        }

        public Criteria andArticleClickIsNotNull() {
            addCriterion("article.article_click is not null");
            return (Criteria) this;
        }

        public Criteria andArticleClickEqualTo(Integer value) {
            addCriterion("article.article_click =", value, "articleClick");
            return (Criteria) this;
        }

        public Criteria andArticleClickNotEqualTo(Integer value) {
            addCriterion("article.article_click <>", value, "articleClick");
            return (Criteria) this;
        }

        public Criteria andArticleClickGreaterThan(Integer value) {
            addCriterion("article.article_click >", value, "articleClick");
            return (Criteria) this;
        }

        public Criteria andArticleClickGreaterThanOrEqualTo(Integer value) {
            addCriterion("article.article_click >=", value, "articleClick");
            return (Criteria) this;
        }

        public Criteria andArticleClickLessThan(Integer value) {
            addCriterion("article.article_click <", value, "articleClick");
            return (Criteria) this;
        }

        public Criteria andArticleClickLessThanOrEqualTo(Integer value) {
            addCriterion("article.article_click <=", value, "articleClick");
            return (Criteria) this;
        }

        public Criteria andArticleClickIn(List<Integer> values) {
            addCriterion("article.article_click in", values, "articleClick");
            return (Criteria) this;
        }

        public Criteria andArticleClickNotIn(List<Integer> values) {
            addCriterion("article.article_click not in", values, "articleClick");
            return (Criteria) this;
        }

        public Criteria andArticleClickBetween(Integer value1, Integer value2) {
            addCriterion("article.article_click between", value1, value2, "articleClick");
            return (Criteria) this;
        }

        public Criteria andArticleClickNotBetween(Integer value1, Integer value2) {
            addCriterion("article.article_click not between", value1, value2, "articleClick");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIsNull() {
            addCriterion("article.article_title is null");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIsNotNull() {
            addCriterion("article.article_title is not null");
            return (Criteria) this;
        }

        public Criteria andArticleTitleEqualTo(String value) {
            addCriterion("article.article_title =", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotEqualTo(String value) {
            addCriterion("article.article_title <>", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleGreaterThan(String value) {
            addCriterion("article.article_title >", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleGreaterThanOrEqualTo(String value) {
            addCriterion("article.article_title >=", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLessThan(String value) {
            addCriterion("article.article_title <", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLessThanOrEqualTo(String value) {
            addCriterion("article.article_title <=", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLike(String value) {
            addCriterion("article.article_title like", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotLike(String value) {
            addCriterion("article.article_title not like", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIn(List<String> values) {
            addCriterion("article.article_title in", values, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotIn(List<String> values) {
            addCriterion("article.article_title not in", values, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleBetween(String value1, String value2) {
            addCriterion("article.article_title between", value1, value2, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotBetween(String value1, String value2) {
            addCriterion("article.article_title not between", value1, value2, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsIsNull() {
            addCriterion("article.article_keywords is null");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsIsNotNull() {
            addCriterion("article.article_keywords is not null");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsEqualTo(String value) {
            addCriterion("article.article_keywords =", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsNotEqualTo(String value) {
            addCriterion("article.article_keywords <>", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsGreaterThan(String value) {
            addCriterion("article.article_keywords >", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("article.article_keywords >=", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsLessThan(String value) {
            addCriterion("article.article_keywords <", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsLessThanOrEqualTo(String value) {
            addCriterion("article.article_keywords <=", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsLike(String value) {
            addCriterion("article.article_keywords like", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsNotLike(String value) {
            addCriterion("article.article_keywords not like", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsIn(List<String> values) {
            addCriterion("article.article_keywords in", values, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsNotIn(List<String> values) {
            addCriterion("article.article_keywords not in", values, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsBetween(String value1, String value2) {
            addCriterion("article.article_keywords between", value1, value2, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsNotBetween(String value1, String value2) {
            addCriterion("article.article_keywords not between", value1, value2, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionIsNull() {
            addCriterion("article.article_description is null");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionIsNotNull() {
            addCriterion("article.article_description is not null");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionEqualTo(String value) {
            addCriterion("article.article_description =", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionNotEqualTo(String value) {
            addCriterion("article.article_description <>", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionGreaterThan(String value) {
            addCriterion("article.article_description >", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("article.article_description >=", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionLessThan(String value) {
            addCriterion("article.article_description <", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionLessThanOrEqualTo(String value) {
            addCriterion("article.article_description <=", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionLike(String value) {
            addCriterion("article.article_description like", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionNotLike(String value) {
            addCriterion("article.article_description not like", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionIn(List<String> values) {
            addCriterion("article.article_description in", values, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionNotIn(List<String> values) {
            addCriterion("article.article_description not in", values, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionBetween(String value1, String value2) {
            addCriterion("article.article_description between", value1, value2, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionNotBetween(String value1, String value2) {
            addCriterion("article.article_description not between", value1, value2, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleFlagIsNull() {
            addCriterion("article.article_flag is null");
            return (Criteria) this;
        }

        public Criteria andArticleFlagIsNotNull() {
            addCriterion("article.article_flag is not null");
            return (Criteria) this;
        }

        public Criteria andArticleFlagEqualTo(String value) {
            addCriterion("article.article_flag =", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagNotEqualTo(String value) {
            addCriterion("article.article_flag <>", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagGreaterThan(String value) {
            addCriterion("article.article_flag >", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagGreaterThanOrEqualTo(String value) {
            addCriterion("article.article_flag >=", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagLessThan(String value) {
            addCriterion("article.article_flag <", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagLessThanOrEqualTo(String value) {
            addCriterion("article.article_flag <=", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagLike(String value) {
            addCriterion("article.article_flag like", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagNotLike(String value) {
            addCriterion("article.article_flag not like", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagIn(List<String> values) {
            addCriterion("article.article_flag in", values, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagNotIn(List<String> values) {
            addCriterion("article.article_flag not in", values, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagBetween(String value1, String value2) {
            addCriterion("article.article_flag between", value1, value2, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagNotBetween(String value1, String value2) {
            addCriterion("article.article_flag not between", value1, value2, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("article.add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("article.add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("article.add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("article.add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("article.add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("article.add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("article.add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("article.add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("article.add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("article.add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("article.add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("article.add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("article.update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("article.update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("article.update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("article.update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("article.update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("article.update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("article.update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("article.update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("article.update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("article.update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("article.update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("article.update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeIsNull() {
            addCriterion("article.del_time is null");
            return (Criteria) this;
        }

        public Criteria andDelTimeIsNotNull() {
            addCriterion("article.del_time is not null");
            return (Criteria) this;
        }

        public Criteria andDelTimeEqualTo(Integer value) {
            addCriterion("article.del_time =", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotEqualTo(Integer value) {
            addCriterion("article.del_time <>", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeGreaterThan(Integer value) {
            addCriterion("article.del_time >", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("article.del_time >=", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeLessThan(Integer value) {
            addCriterion("article.del_time <", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeLessThanOrEqualTo(Integer value) {
            addCriterion("article.del_time <=", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeIn(List<Integer> values) {
            addCriterion("article.del_time in", values, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotIn(List<Integer> values) {
            addCriterion("article.del_time not in", values, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeBetween(Integer value1, Integer value2) {
            addCriterion("article.del_time between", value1, value2, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("article.del_time not between", value1, value2, "delTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content_article
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 04 10:36:30 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table content_article
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}