package edu.xww.db.model;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString(callSuper=true)
public class ContentBanner extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_banner.banner_name
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String bannerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_banner.banner_sort
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private Integer bannerSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_banner.banner_url
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String bannerUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_banner.banner_thumb
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String bannerThumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_banner.banner_position
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String bannerPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_banner.open_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String openType;
}