package edu.xww.db.model;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString(callSuper=true)
public class SystemConfig extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.config_name
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String configName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.config_key
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String configKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.config_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String configType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.config_value
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String configValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_config.config_des
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String configDes;
}