package edu.xww.db.model;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString(callSuper=true)
public class SystemLink extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_link.link_name
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_link.link_url
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String linkUrl;
}