package edu.xww.db.model;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString(callSuper=true)
public class SystemTemplate extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_template.template_type
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String templateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_template.template_name
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_template.template_dir
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String templateDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_template.template_file
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String templateFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_template.template_thumb
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String templateThumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_template.template_des
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String templateDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_template.template_content
     *
     * @mbg.generated Thu Nov 04 10:36:30 CST 2021
     */
    private String templateContent;
}